This notebook will show the summary statistics in my report

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('FINAL_DATASET.csv')
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,latitude,longitude,weather_tempmax,weather_tempmin,weather_temp,weather_feelslikemax,weather_feelslikemin,...,Activity_Snowmobiling,Activity_Snowshoeing,Activity_Suicide,Activity_Swimming,Activity_Undetermined,Activity_Vessel Related,Activity_Wading,Activity_Walking,Activity_Wildlife watching,Cause of Death
0,0,1,1.0,37.849927,-122.517752,59.6,41.2,49.0,59.6,37.4,...,False,False,False,False,False,True,False,False,False,Drowning
1,1,2,2.0,37.849927,-122.517752,59.6,41.2,49.0,59.6,37.4,...,False,False,False,False,False,True,False,False,False,Undetermined
2,2,3,3.0,32.007155,-90.858514,45.3,21.7,34.4,42.3,21.7,...,False,False,False,False,False,False,False,False,False,Motor Vehicle Crash
3,3,4,4.0,32.007155,-90.858514,45.3,21.7,34.4,42.3,21.7,...,False,False,False,False,False,False,False,False,False,Motor Vehicle Crash
4,4,5,5.0,40.598479,-73.857927,26.0,13.9,19.6,13.8,1.0,...,False,False,False,False,False,False,False,False,False,Undetermined

In [4]:
columns_to_keep = [col for col in df.columns if not (col.startswith('Unnamed:') or col.startswith('Activity'))]

df = df[columns_to_keep]

In [8]:
#For all classes

y = pd.DataFrame(df['Cause of Death'])

X = df.drop(columns=[col for col in df.columns if col.startswith('Cause of Death')], errors='ignore')


print(f"original dataset shape: {X.shape}")


# Display unique classes in the original target variable
print("Original target variable:")
print(y.value_counts())  # Assuming y is a pandas Series

original dataset shape: (4545, 545)
Original target variable:
Cause of Death
Drowning                                  844
Motor Vehicle Crash                       820
Suicide                                   642
Undetermined                              585
Fall                                      489
Medical - During physical activity        317
Medical - Not during physical activity    237
Medical - Unknown                          82
Hyperthermia                               80
Homicide                                   50
Aircraft incident                          46
Hypothermia                                44
Avalanche                                  41
Vessel Incident                            31
Aircraft Incident                          26
Poisoning - drugs                          24
Bicycle only crash                         22
Poisoning - Drugs                          21
Falling tree/branch                        21
Rockfall                                   20
Vessel Incident                            15
Flash flood                                12
Widlife incident                           10
Asphyxiation                                7
Lightning strike                            6
Other                                       6
Skiing Incident                             5
Electrocution                               4
Train crash                                 4
Lightning Strike                            4
Poisoning - alcohol                         4
Firearm                                     4
Poisoning - Carbon monoxide                 4
Fire/Burn                                   3
Horseback riding incident                   3
Fire/burn                                   2
Legal Intervention                          2
Struck by/against                           2
Falling Ice                                 2
Collapsing earth/sand                       2
Skateboard Incident                         2
Name: count, dtype: int64

In [9]:
#For just Drowning guy
# Separate features (X) and target variable (y)
y = pd.DataFrame(df['Cause of Death'])

# Assuming y is a DataFrame with a column 'Cause of Death'
y['binary_label'] = y['Cause of Death'].apply(lambda x: 1 if x == 'Drowning' else 0)
# Assuming `y` is your DataFrame
y = y.drop(columns=['Cause of Death'])
# Rename the column
y = y.rename(columns={'binary_label': 'Cause of Death'})

# Assuming y contains the original labels
#y_binary = y.apply(lambda label: 1 if label == 'Drowning' else 0)
#y = y_binary
# Train-test split
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, stratify=y_binary, random_state=42)


X = df.drop(columns=[col for col in df.columns if col.startswith('Cause of Death')], errors='ignore')
X = X.drop(columns=[col for col in X.columns if col.startswith('Death')], errors='ignore')

In [10]:
# Encode all non-numeric columns
non_numeric_columns = df.select_dtypes(include=['object', 'category']).columns
print(f"Non-numerical columns detected: {list(non_numeric_columns)}")

df_encoded = pd.get_dummies(df, columns=non_numeric_columns, drop_first=True)
print("Shape of DataFrame after encoding:", df_encoded.shape)

# Separate features (X) and target variable (y)
X = df_encoded.drop(columns=[col for col in df_encoded.columns if col.startswith('Cause of Death_') or col.startswith('Death')], errors='ignore')

Non-numerical columns detected: ['Cause of Death']
Shape of DataFrame after encoding: (4545, 585)

In [ ]:
import pandas as pd

df.describe()  # For numerical columns
#df.describe(include=['object'])  # For categorical columns
# Get the descriptive statistics
description = df.describe()


# Save to a text file
with open('summary_statistics.txt', 'w') as f:
    f.write(description.to_string())

<class 'pandas.core.frame.DataFrame'>

In [15]:
# Print the first 5 columns
print(df.describe().iloc[:, :5])

          latitude    longitude  weather_tempmax  weather_tempmin  \
count  4545.000000  4545.000000      4545.000000      4545.000000
mean     38.187315   -97.581759        73.568361        52.134873
std       6.112308    26.511134        17.497907        17.211141
min      13.402746  -156.132430         1.300000       -25.700000
25%      35.883757  -114.690120        62.200000        40.700000
50%      37.839300  -104.900737        76.000000        52.900000
75%      40.355392   -81.077598        85.900000        64.900000
max      63.231662   145.718442       116.400000        93.500000

       weather_temp
count   4545.000000
mean      62.661496
std       16.778215
min      -10.600000
25%       51.800000
50%       64.200000
75%       74.800000
max      106.700000

In [16]:
df.describe(include=['object'])

       Cause of Death
count            4545
unique             41
top          Drowning
freq              844